apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs
  name: nodejs
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nodejs
    spec:
      containers:
      - args:
        - ./wait-for.sh
        - db:27017
        - --
        - /home/node/app/node_modules/.bin/nodemon
        - app.js
        env:
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              key: MONGO_DB
              name: nodejs-env
        - name: MONGO_HOSTNAME
          value: db
        - name: MONGO_PASSWORD
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              key: MONGO_PORT
              name: nodejs-env
        - name: jouad
        image: jouad/node-kubernetes
        name: nodejs
        ports:
        - containerPort: 8080
        resources: {}
      initContainers:
        - name: init-db
          image: busybox
          command: ['sh', '-c', 'until nc -z db:27017; do echo waiting for db; sleep2; done;']
        volumeMounts:
        - mountPath: /home/node/app
          name: nodejs-claim0
        - mountPath: /home/node/app/node_modules
          name: node-modules
      restartPolicy: Always
      volumes:
      - name: nodejs-claim0
        persistentVolumeClaim:
          claimName: nodejs-claim0
      - name: node-modules
        persistentVolumeClaim:
          claimName: node-modules
status: {}
